spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/dsa_leveling
spring.datasource.username=postgres
spring.datasource.password=Hemanth@zcxv

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT Configuration
jwt.secret=izFI2V/LA3FwiWWOiQryYeRj0bWMPQBPR+es6aJ6kHc=
jwt.expiration=86400000

# Logging
logging.level.backend=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG